#!/bin/bash
ngpid=$(pgrep -f "ngp-loop.sh ")

if [ "$ngpid" != "" ]; then
	if [ "$1" == "stop" ]; then
		kill $ngpid
		kill $(pgrep ngp-bin)
		echo "NGP program stopped"
		exit
	fi

	echo "Already running [$ngpid]"
	exit

elif [ "$1" == "stop" ]; then
    echo "ngp is not running"
    exit
fi

make

if [ ! -f primes.dat ]; then
    echo "primes.dat not found, running sieve thru 2^32:"
    ./psieve
fi

if [ "$#" -ne "6" ]; then
    read -p "Starting value      : " var[0]
    read -p "Stopping value      : " var[1]
    read -p "Thread Chunk Size   : " var[2]
    read -p "Write to file every : " var[3]
    read -p "Output directory    : " outdir
    read -p "Log file path       : " logfile
else
    var[0]=$1
    var[1]=$2
    var[2]=$3
    var[3]=$4
    outdir=$5
    logfile=$6
fi

for i in {0..3}; do
    var_sep[i]=$(python3 -c "print(f\"{int(${var[i]}):,d}\")")
    var[i]=$(python3 -c "print(int(${var[i]}))")
done

echo
echo "-----------NEW BATCH------------"
echo "Starting value      : ${var_sep[0]}"
echo "Stopping value      : ${var_sep[1]}"
echo "Thread Chunk Size   : ${var_sep[2]}"
echo "# Residue classes   : 1000"
echo "Write to file every : ${var_sep[3]}"
echo "Output directory    : $outdir"
echo "Log file path       : $logfile"

nohup "./ngp-loop.sh" ${var[0]} ${var[1]} ${var[2]} ${var[3]} $outdir $logfile >> /dev/null 2>&1 &
